flowdock_api_key: <your-api-key>  # your flowdock api key
#storage_path: /tmp               # the path to store notifications (defalt /tmp/flowdock_notifications)
#ping_prefix: 0x21                # the character by which pings are identified (default !)
#role_prefix: 0x26                # the character to modify roles (default &)
